import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import PostCard from "../components/PostCard";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import { createClient } from "contentful";
import Navigation from "../components/Navigation";
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Munfraid - Latest Blog Update </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {console.log(posts)}
        <div>
          <Sidebar />
        </div>
        <div className={styles.postWrapper}>
          {/* <PostCard />
          <PostCard />
          <PostCard /> */}

          {posts.map((post) => (
            <PostCard key={post.sys.id} post={post} />
          ))}
        </div>
      </main>
      <Navigation />
    </div>
  );
}

export async function getStaticProps() {
  const client = createClient({
    space: "saquqkssf24q",
    accessToken: "_VwJbRSzYMmM-5SeMt9xOe2EkIUdcBeHLTZMvSWR_-g",
  });

  // const posts = client.getEntry("blogpost").then((entry) => {
  //   return entry;
  // });

  const posts = await client.getEntries().then(function (entries) {
    return entries.items;
  });

  return {
    props: {
      posts,
    },
  };
}
